### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by sangjunp4rk** [makizmo/f1-3-c2p1-colmar-academy#5]
Summary Grade: Satisfactory

I like the way you used classes and ids to group your sections together. As your code grows in size, this will help organize and manage your website. You also gave a good effort into your mobile resizing. Great start to the Ready program! 

I included a few notes in both the html and css files for you to think more critically about. You can find these comments in the issues tab of your github. The most important thing is to use indentation to organize your code. Because everything is on the same level, it is difficult to tell where one section begins and end. Make sure to nest your code. Also, spend some more time with mobile resizing. There is some picture distortion at the smaller screen widths.

**Comment by makizmo** [comment]
Thank you Sang.
I am glad you reviewed my codes.
I'll definitely work on the comments.
